### ISSUE TITLE
Suggestion: rename hx

### ISSUE THREAD

**Issue by xor** [sitkevij/hex#71]
I was unable to install hex because https://github.com/helix-editor/helix has `hx`.

```sh
$ cargo install hx
error: binary `hx` already exists in destination as part of `helix-term v0.6.0 (/home/x/helix/helix-term)`
Add --force to overwrite
```

**Comment by sitkevij** [comment]
The **hx** binary is registered at https://crates.io/crates/hx, the Rust community's crate registry.

**Comment by k4lizen** [comment]
Is there a recommended way to install this alongside helix? (im on arch/artix specifically)

**Comment by guija** [comment]
I also wanted to follow up on this. Any recommendations for how to install it alongside helix?
I think helix has gained a lot of traction the last months, maybe renaming your tool or suggesting a workaround would help you to gain adoption. I fear that otherwise people will stick to the regular hexdump of util-linux.
